//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAYENE_TAKIP.DBOBJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANABILIMDALI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANABILIMDALI()
        {
            this.DOKTOR = new HashSet<DOKTOR>();
        }
    
        public int ANABILIMDALIID { get; set; }
        public string ADI { get; set; }
        public string ACIKLAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOKTOR> DOKTOR { get; set; }
    }
}
