//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAYENE_TAKIP.DBOBJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUAYENE
    {
        public int MUAYENEID { get; set; }
        public int RANDEVUID { get; set; }
        public string TESHIS { get; set; }
        public string TEDAVI { get; set; }
    
        public virtual RANDEVU RANDEVU { get; set; }
    }
}
