//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAYENE_TAKIP.DBOBJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANDEVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RANDEVU()
        {
            this.MUAYENE = new HashSet<MUAYENE>();
        }
    
        public int RANDEVUID { get; set; }
        public int DOKTORID { get; set; }
        public int HASTAID { get; set; }
        public System.DateTime MUAYENETARIH { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual DOKTOR DOKTOR { get; set; }
        public virtual HASTA HASTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUAYENE> MUAYENE { get; set; }
    }
}
